In [44]:
import pandas as pd
import numpy as np
from numpy.random import randn

In [ ]:
train = pd.read_csv("train.csv")
test = pd.read_csv('test.csv')

In [ ]:
train.head()

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
modelo = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0)

In [ ]:
train['Sex'].value_counts()

In [ ]:
def tranformar_sexo(valor):
    if valor == 'female':
        return 1
    else:
        return 0

train['Sex_binario'] = train['Sex'].map(tranformar_sexo)

In [ ]:
train.head()

In [ ]:
variaveis = ['Sex_binario', 'Age']

In [ ]:
X = train[variaveis]
Y = train['Survived']

In [ ]:
X.head()

In [40]:
np.empty((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [45]:
name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = randn(7, 4)

In [49]:
print(name)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-0.34771106 -0.08829082  0.67119022  0.54201279]
 [-1.2017691   0.06069372 -0.85417764  1.11917123]
 [ 0.30352683 -0.9869287  -0.44146646 -0.42788663]
 [-0.49097313 -0.47993847 -0.52957627  1.99540956]
 [ 0.57730515  2.06968497 -0.277535    1.07718849]
 [ 0.48048396  1.40639665 -0.16186883 -0.13880019]
 [ 1.33557314  0.71681998 -1.35575009  2.0461746 ]]


In [50]:
name == 'Bob'

array([ True, False, False,  True, False, False, False])

In [69]:
arr = np.arange(32).reshape([8, 4])
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [87]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [93]:
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])